global:
  scrape_interval: 5s  # Scrape every 5 seconds

scrape_configs:
  - job_name: 'roman-converter'
    static_configs:
      - targets: ['roman-converter:8080']
    metrics_path: '/metrics'  # The endpoint where metrics are exposed
